// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: F-105_AccountCreateReq.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//创建账号请求
type AccountCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 新账号
	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// 昵称(默认为账号)
	NickName string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	// 账号所属公会
	AccountBelong string `protobuf:"bytes,3,opt,name=accountBelong,proto3" json:"accountBelong,omitempty"`
	// 游戏ID
	GameId int32 `protobuf:"varint,4,opt,name=gameId,proto3" json:"gameId,omitempty"`
	// 平台
	PlatformId int32 `protobuf:"varint,5,opt,name=platformId,proto3" json:"platformId,omitempty"`
	// 游戏模式(官游/野游)
	ModeId int32 `protobuf:"varint,6,opt,name=modeId,proto3" json:"modeId,omitempty"`
	// 预充值额度(RMB)
	Money float64 `protobuf:"fixed64,9,opt,name=money,proto3" json:"money,omitempty"`
	// 流水比例
	MoneyRate float64 `protobuf:"fixed64,10,opt,name=moneyRate,proto3" json:"moneyRate,omitempty"`
	// 管理员密码
	AdminPassword string `protobuf:"bytes,11,opt,name=adminPassword,proto3" json:"adminPassword,omitempty"`
}

func (x *AccountCreateReq) Reset() {
	*x = AccountCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_F_105_AccountCreateReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreateReq) ProtoMessage() {}

func (x *AccountCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_F_105_AccountCreateReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreateReq.ProtoReflect.Descriptor instead.
func (*AccountCreateReq) Descriptor() ([]byte, []int) {
	return file_F_105_AccountCreateReq_proto_rawDescGZIP(), []int{0}
}

func (x *AccountCreateReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountCreateReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *AccountCreateReq) GetAccountBelong() string {
	if x != nil {
		return x.AccountBelong
	}
	return ""
}

func (x *AccountCreateReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *AccountCreateReq) GetPlatformId() int32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *AccountCreateReq) GetModeId() int32 {
	if x != nil {
		return x.ModeId
	}
	return 0
}

func (x *AccountCreateReq) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *AccountCreateReq) GetMoneyRate() float64 {
	if x != nil {
		return x.MoneyRate
	}
	return 0
}

func (x *AccountCreateReq) GetAdminPassword() string {
	if x != nil {
		return x.AdminPassword
	}
	return ""
}

var File_F_105_AccountCreateReq_proto protoreflect.FileDescriptor

var file_F_105_AccountCreateReq_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x46, 0x2d, 0x31, 0x30, 0x35, 0x5f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x9c, 0x02, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x65, 0x6c, 0x6f,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x65, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_F_105_AccountCreateReq_proto_rawDescOnce sync.Once
	file_F_105_AccountCreateReq_proto_rawDescData = file_F_105_AccountCreateReq_proto_rawDesc
)

func file_F_105_AccountCreateReq_proto_rawDescGZIP() []byte {
	file_F_105_AccountCreateReq_proto_rawDescOnce.Do(func() {
		file_F_105_AccountCreateReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_F_105_AccountCreateReq_proto_rawDescData)
	})
	return file_F_105_AccountCreateReq_proto_rawDescData
}

var file_F_105_AccountCreateReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_F_105_AccountCreateReq_proto_goTypes = []interface{}{
	(*AccountCreateReq)(nil), // 0: pb.AccountCreateReq
}
var file_F_105_AccountCreateReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_F_105_AccountCreateReq_proto_init() }
func file_F_105_AccountCreateReq_proto_init() {
	if File_F_105_AccountCreateReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_F_105_AccountCreateReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_F_105_AccountCreateReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_F_105_AccountCreateReq_proto_goTypes,
		DependencyIndexes: file_F_105_AccountCreateReq_proto_depIdxs,
		MessageInfos:      file_F_105_AccountCreateReq_proto_msgTypes,
	}.Build()
	File_F_105_AccountCreateReq_proto = out.File
	file_F_105_AccountCreateReq_proto_rawDesc = nil
	file_F_105_AccountCreateReq_proto_goTypes = nil
	file_F_105_AccountCreateReq_proto_depIdxs = nil
}
