// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: F-1104_YeYouDanMuLoginReq.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//野游弹幕登录请求
type YeYouDanMuLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 账号
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// 直播间地址
	RoomId string `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *YeYouDanMuLoginReq) Reset() {
	*x = YeYouDanMuLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_F_1104_YeYouDanMuLoginReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YeYouDanMuLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YeYouDanMuLoginReq) ProtoMessage() {}

func (x *YeYouDanMuLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_F_1104_YeYouDanMuLoginReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YeYouDanMuLoginReq.ProtoReflect.Descriptor instead.
func (*YeYouDanMuLoginReq) Descriptor() ([]byte, []int) {
	return file_F_1104_YeYouDanMuLoginReq_proto_rawDescGZIP(), []int{0}
}

func (x *YeYouDanMuLoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *YeYouDanMuLoginReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_F_1104_YeYouDanMuLoginReq_proto protoreflect.FileDescriptor

var file_F_1104_YeYouDanMuLoginReq_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x46, 0x2d, 0x31, 0x31, 0x30, 0x34, 0x5f, 0x59, 0x65, 0x59, 0x6f, 0x75, 0x44, 0x61,
	0x6e, 0x4d, 0x75, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x46, 0x0a, 0x12, 0x59, 0x65, 0x59, 0x6f, 0x75, 0x44, 0x61,
	0x6e, 0x4d, 0x75, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_F_1104_YeYouDanMuLoginReq_proto_rawDescOnce sync.Once
	file_F_1104_YeYouDanMuLoginReq_proto_rawDescData = file_F_1104_YeYouDanMuLoginReq_proto_rawDesc
)

func file_F_1104_YeYouDanMuLoginReq_proto_rawDescGZIP() []byte {
	file_F_1104_YeYouDanMuLoginReq_proto_rawDescOnce.Do(func() {
		file_F_1104_YeYouDanMuLoginReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_F_1104_YeYouDanMuLoginReq_proto_rawDescData)
	})
	return file_F_1104_YeYouDanMuLoginReq_proto_rawDescData
}

var file_F_1104_YeYouDanMuLoginReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_F_1104_YeYouDanMuLoginReq_proto_goTypes = []interface{}{
	(*YeYouDanMuLoginReq)(nil), // 0: pb.YeYouDanMuLoginReq
}
var file_F_1104_YeYouDanMuLoginReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_F_1104_YeYouDanMuLoginReq_proto_init() }
func file_F_1104_YeYouDanMuLoginReq_proto_init() {
	if File_F_1104_YeYouDanMuLoginReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_F_1104_YeYouDanMuLoginReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YeYouDanMuLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_F_1104_YeYouDanMuLoginReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_F_1104_YeYouDanMuLoginReq_proto_goTypes,
		DependencyIndexes: file_F_1104_YeYouDanMuLoginReq_proto_depIdxs,
		MessageInfos:      file_F_1104_YeYouDanMuLoginReq_proto_msgTypes,
	}.Build()
	File_F_1104_YeYouDanMuLoginReq_proto = out.File
	file_F_1104_YeYouDanMuLoginReq_proto_rawDesc = nil
	file_F_1104_YeYouDanMuLoginReq_proto_goTypes = nil
	file_F_1104_YeYouDanMuLoginReq_proto_depIdxs = nil
}
