// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: F-601_AccountCountReq.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//直播账号统计请求
type AccountCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 数据前缀
	DataFixVo *AccountCountDataFixVo `protobuf:"bytes,1,opt,name=dataFixVo,proto3" json:"dataFixVo,omitempty"`
	// 管理员密码
	AdminPassword string `protobuf:"bytes,2,opt,name=adminPassword,proto3" json:"adminPassword,omitempty"`
	// 查询时间 (当日凌晨时间戳秒)
	ViewTime int64 `protobuf:"varint,3,opt,name=viewTime,proto3" json:"viewTime,omitempty"`
	// 查询下标,从0开始
	StartIndex int32 `protobuf:"varint,4,opt,name=startIndex,proto3" json:"startIndex,omitempty"`
	// 查询下标,从0开始
	EndIndex int32 `protobuf:"varint,5,opt,name=endIndex,proto3" json:"endIndex,omitempty"`
	// 排序 1每日 2总
	SortType int32 `protobuf:"varint,6,opt,name=sortType,proto3" json:"sortType,omitempty"`
	// 主播id
	AccountId string `protobuf:"bytes,7,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// 公告
	Notice  string `protobuf:"bytes,8,opt,name=notice,proto3" json:"notice,omitempty"`
	Page    int32  `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	Limit   int32  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	MsgCode int32  `protobuf:"varint,11,opt,name=MsgCode,proto3" json:"MsgCode,omitempty"` //消息code 0成功 1失败
}

func (x *AccountCountReq) Reset() {
	*x = AccountCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_F_601_AccountCountReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCountReq) ProtoMessage() {}

func (x *AccountCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_F_601_AccountCountReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCountReq.ProtoReflect.Descriptor instead.
func (*AccountCountReq) Descriptor() ([]byte, []int) {
	return file_F_601_AccountCountReq_proto_rawDescGZIP(), []int{0}
}

func (x *AccountCountReq) GetDataFixVo() *AccountCountDataFixVo {
	if x != nil {
		return x.DataFixVo
	}
	return nil
}

func (x *AccountCountReq) GetAdminPassword() string {
	if x != nil {
		return x.AdminPassword
	}
	return ""
}

func (x *AccountCountReq) GetViewTime() int64 {
	if x != nil {
		return x.ViewTime
	}
	return 0
}

func (x *AccountCountReq) GetStartIndex() int32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *AccountCountReq) GetEndIndex() int32 {
	if x != nil {
		return x.EndIndex
	}
	return 0
}

func (x *AccountCountReq) GetSortType() int32 {
	if x != nil {
		return x.SortType
	}
	return 0
}

func (x *AccountCountReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountCountReq) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *AccountCountReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AccountCountReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AccountCountReq) GetMsgCode() int32 {
	if x != nil {
		return x.MsgCode
	}
	return 0
}

type AccountCountDataFixVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏ID
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	// 平台
	PlatformId int32 `protobuf:"varint,2,opt,name=platformId,proto3" json:"platformId,omitempty"`
	// 地区
	RegionId int32 `protobuf:"varint,3,opt,name=regionId,proto3" json:"regionId,omitempty"`
	// 游戏模式/官游/野游
	ModeId int32 `protobuf:"varint,4,opt,name=modeId,proto3" json:"modeId,omitempty"`
	// 区服
	Partition int32 `protobuf:"varint,5,opt,name=partition,proto3" json:"partition,omitempty"`
}

func (x *AccountCountDataFixVo) Reset() {
	*x = AccountCountDataFixVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_F_601_AccountCountReq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCountDataFixVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCountDataFixVo) ProtoMessage() {}

func (x *AccountCountDataFixVo) ProtoReflect() protoreflect.Message {
	mi := &file_F_601_AccountCountReq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCountDataFixVo.ProtoReflect.Descriptor instead.
func (*AccountCountDataFixVo) Descriptor() ([]byte, []int) {
	return file_F_601_AccountCountReq_proto_rawDescGZIP(), []int{1}
}

func (x *AccountCountDataFixVo) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *AccountCountDataFixVo) GetPlatformId() int32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *AccountCountDataFixVo) GetRegionId() int32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *AccountCountDataFixVo) GetModeId() int32 {
	if x != nil {
		return x.ModeId
	}
	return 0
}

func (x *AccountCountDataFixVo) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

var File_F_601_AccountCountReq_proto protoreflect.FileDescriptor

var file_F_601_AccountCountReq_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x46, 0x2d, 0x36, 0x30, 0x31, 0x5f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0xde, 0x02, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x78,
	0x56, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x46, 0x69,
	0x78, 0x56, 0x6f, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x78, 0x56, 0x6f, 0x12, 0x24,
	0x0a, 0x0d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x76, 0x69, 0x65, 0x77, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x46, 0x69, 0x78, 0x56, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_F_601_AccountCountReq_proto_rawDescOnce sync.Once
	file_F_601_AccountCountReq_proto_rawDescData = file_F_601_AccountCountReq_proto_rawDesc
)

func file_F_601_AccountCountReq_proto_rawDescGZIP() []byte {
	file_F_601_AccountCountReq_proto_rawDescOnce.Do(func() {
		file_F_601_AccountCountReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_F_601_AccountCountReq_proto_rawDescData)
	})
	return file_F_601_AccountCountReq_proto_rawDescData
}

var file_F_601_AccountCountReq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_F_601_AccountCountReq_proto_goTypes = []interface{}{
	(*AccountCountReq)(nil),       // 0: pb.AccountCountReq
	(*AccountCountDataFixVo)(nil), // 1: pb.AccountCountDataFixVo
}
var file_F_601_AccountCountReq_proto_depIdxs = []int32{
	1, // 0: pb.AccountCountReq.dataFixVo:type_name -> pb.AccountCountDataFixVo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_F_601_AccountCountReq_proto_init() }
func file_F_601_AccountCountReq_proto_init() {
	if File_F_601_AccountCountReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_F_601_AccountCountReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_F_601_AccountCountReq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCountDataFixVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_F_601_AccountCountReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_F_601_AccountCountReq_proto_goTypes,
		DependencyIndexes: file_F_601_AccountCountReq_proto_depIdxs,
		MessageInfos:      file_F_601_AccountCountReq_proto_msgTypes,
	}.Build()
	File_F_601_AccountCountReq_proto = out.File
	file_F_601_AccountCountReq_proto_rawDesc = nil
	file_F_601_AccountCountReq_proto_goTypes = nil
	file_F_601_AccountCountReq_proto_depIdxs = nil
}
