// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: ModeId.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//message ModeId {
//// 官游
// ModeId GuanYou=1;
//// 野游
// ModeId YeYou=2;
//}
type ModeId int32

const (
	ModeId_ModeIdNone ModeId = 0
	ModeId_GuanYou    ModeId = 1
	ModeId_YeYou      ModeId = 2
)

// Enum value maps for ModeId.
var (
	ModeId_name = map[int32]string{
		0: "ModeIdNone",
		1: "GuanYou",
		2: "YeYou",
	}
	ModeId_value = map[string]int32{
		"ModeIdNone": 0,
		"GuanYou":    1,
		"YeYou":      2,
	}
)

func (x ModeId) Enum() *ModeId {
	p := new(ModeId)
	*p = x
	return p
}

func (x ModeId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModeId) Descriptor() protoreflect.EnumDescriptor {
	return file_ModeId_proto_enumTypes[0].Descriptor()
}

func (ModeId) Type() protoreflect.EnumType {
	return &file_ModeId_proto_enumTypes[0]
}

func (x ModeId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModeId.Descriptor instead.
func (ModeId) EnumDescriptor() ([]byte, []int) {
	return file_ModeId_proto_rawDescGZIP(), []int{0}
}

var File_ModeId_proto protoreflect.FileDescriptor

var file_ModeId_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x2a, 0x30, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x0a,
	0x4d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x47, 0x75, 0x61, 0x6e, 0x59, 0x6f, 0x75, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x59, 0x65, 0x59,
	0x6f, 0x75, 0x10, 0x02, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ModeId_proto_rawDescOnce sync.Once
	file_ModeId_proto_rawDescData = file_ModeId_proto_rawDesc
)

func file_ModeId_proto_rawDescGZIP() []byte {
	file_ModeId_proto_rawDescOnce.Do(func() {
		file_ModeId_proto_rawDescData = protoimpl.X.CompressGZIP(file_ModeId_proto_rawDescData)
	})
	return file_ModeId_proto_rawDescData
}

var file_ModeId_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ModeId_proto_goTypes = []interface{}{
	(ModeId)(0), // 0: pb.ModeId
}
var file_ModeId_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ModeId_proto_init() }
func file_ModeId_proto_init() {
	if File_ModeId_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ModeId_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ModeId_proto_goTypes,
		DependencyIndexes: file_ModeId_proto_depIdxs,
		EnumInfos:         file_ModeId_proto_enumTypes,
	}.Build()
	File_ModeId_proto = out.File
	file_ModeId_proto_rawDesc = nil
	file_ModeId_proto_goTypes = nil
	file_ModeId_proto_depIdxs = nil
}
