// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: PlatformId.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//message PlatformId {
//// Tiktok
// PlatformId Tiktok=1;
//// 视频号
// PlatformId ShiPinHao=2;
//// 快手
// PlatformId KuaiShou=3;
//// B站
// PlatformId BZhan=4;
//// 抖音
// PlatformId DouYin=5;
//// QQ
// PlatformId QQ=6;
//}
type PlatformId int32

const (
	PlatformId_PlatformIdNone PlatformId = 0
	PlatformId_Tiktok         PlatformId = 1
	PlatformId_ShiPinHao      PlatformId = 2
	PlatformId_KuaiShou       PlatformId = 3
	PlatformId_BZhan          PlatformId = 4
	PlatformId_DouYin         PlatformId = 5
	PlatformId_QQ             PlatformId = 6
	PlatformId_MM             PlatformId = 7 //陌陌
	PlatformId_Hy             PlatformId = 8 //虎牙
	PlatformId_Lrs            PlatformId = 9 //狼人杀
	//Dyhh
	PlatformId_TkHh PlatformId = 15 // tk自己的盒子平台
	PlatformId_DyHh PlatformId = 16 // dy自己的盒子平台
)

// Enum value maps for PlatformId.
var (
	PlatformId_name = map[int32]string{
		0:  "PlatformIdNone",
		1:  "Tiktok",
		2:  "ShiPinHao",
		3:  "KuaiShou",
		4:  "BZhan",
		5:  "DouYin",
		6:  "QQ",
		7:  "MM",
		8:  "Hy",
		9:  "Lrs",
		15: "TkHh",
		16: "DyHh",
	}
	PlatformId_value = map[string]int32{
		"PlatformIdNone": 0,
		"Tiktok":         1,
		"ShiPinHao":      2,
		"KuaiShou":       3,
		"BZhan":          4,
		"DouYin":         5,
		"QQ":             6,
		"MM":             7,
		"Hy":             8,
		"Lrs":            9,
		"TkHh":           15,
		"DyHh":           16,
	}
)

func (x PlatformId) Enum() *PlatformId {
	p := new(PlatformId)
	*p = x
	return p
}

func (x PlatformId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformId) Descriptor() protoreflect.EnumDescriptor {
	return file_PlatformId_proto_enumTypes[0].Descriptor()
}

func (PlatformId) Type() protoreflect.EnumType {
	return &file_PlatformId_proto_enumTypes[0]
}

func (x PlatformId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformId.Descriptor instead.
func (PlatformId) EnumDescriptor() ([]byte, []int) {
	return file_PlatformId_proto_rawDescGZIP(), []int{0}
}

var File_PlatformId_proto protoreflect.FileDescriptor

var file_PlatformId_proto_rawDesc = []byte{
	0x0a, 0x10, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x95, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x49, 0x64, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x69, 0x6b,
	0x74, 0x6f, 0x6b, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x68, 0x69, 0x50, 0x69, 0x6e, 0x48,
	0x61, 0x6f, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4b, 0x75, 0x61, 0x69, 0x53, 0x68, 0x6f, 0x75,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x5a, 0x68, 0x61, 0x6e, 0x10, 0x04, 0x12, 0x0a, 0x0a,
	0x06, 0x44, 0x6f, 0x75, 0x59, 0x69, 0x6e, 0x10, 0x05, 0x12, 0x06, 0x0a, 0x02, 0x51, 0x51, 0x10,
	0x06, 0x12, 0x06, 0x0a, 0x02, 0x4d, 0x4d, 0x10, 0x07, 0x12, 0x06, 0x0a, 0x02, 0x48, 0x79, 0x10,
	0x08, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x72, 0x73, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x6b,
	0x48, 0x68, 0x10, 0x0f, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x79, 0x48, 0x68, 0x10, 0x10, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PlatformId_proto_rawDescOnce sync.Once
	file_PlatformId_proto_rawDescData = file_PlatformId_proto_rawDesc
)

func file_PlatformId_proto_rawDescGZIP() []byte {
	file_PlatformId_proto_rawDescOnce.Do(func() {
		file_PlatformId_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlatformId_proto_rawDescData)
	})
	return file_PlatformId_proto_rawDescData
}

var file_PlatformId_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PlatformId_proto_goTypes = []interface{}{
	(PlatformId)(0), // 0: pb.PlatformId
}
var file_PlatformId_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PlatformId_proto_init() }
func file_PlatformId_proto_init() {
	if File_PlatformId_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlatformId_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlatformId_proto_goTypes,
		DependencyIndexes: file_PlatformId_proto_depIdxs,
		EnumInfos:         file_PlatformId_proto_enumTypes,
	}.Build()
	File_PlatformId_proto = out.File
	file_PlatformId_proto_rawDesc = nil
	file_PlatformId_proto_goTypes = nil
	file_PlatformId_proto_depIdxs = nil
}
