// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: slg.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 农民枚举
type FarmerType int32

const (
	// 挖矿
	FarmerType_Farmer_Mine FarmerType = 0
	// 步兵士
	FarmerType_Farmer_Infantry FarmerType = 1
	// 弓箭手
	FarmerType_Farmer_Archer FarmerType = 2
	// 骑兵士
	FarmerType_Farmer_Cavalry FarmerType = 3
)

// Enum value maps for FarmerType.
var (
	FarmerType_name = map[int32]string{
		0: "Farmer_Mine",
		1: "Farmer_Infantry",
		2: "Farmer_Archer",
		3: "Farmer_Cavalry",
	}
	FarmerType_value = map[string]int32{
		"Farmer_Mine":     0,
		"Farmer_Infantry": 1,
		"Farmer_Archer":   2,
		"Farmer_Cavalry":  3,
	}
)

func (x FarmerType) Enum() *FarmerType {
	p := new(FarmerType)
	*p = x
	return p
}

func (x FarmerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FarmerType) Descriptor() protoreflect.EnumDescriptor {
	return file_slg_proto_enumTypes[0].Descriptor()
}

func (FarmerType) Type() protoreflect.EnumType {
	return &file_slg_proto_enumTypes[0]
}

func (x FarmerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FarmerType.Descriptor instead.
func (FarmerType) EnumDescriptor() ([]byte, []int) {
	return file_slg_proto_rawDescGZIP(), []int{0}
}

var File_slg_proto protoreflect.FileDescriptor

var file_slg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6c, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a,
	0x59, 0x0a, 0x0a, 0x46, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x46, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x5f, 0x4d, 0x69, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x46, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x5f, 0x49, 0x6e, 0x66, 0x61, 0x6e, 0x74, 0x72,
	0x79, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x61, 0x72, 0x6d, 0x65, 0x72, 0x5f, 0x41, 0x72,
	0x63, 0x68, 0x65, 0x72, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x61, 0x72, 0x6d, 0x65, 0x72,
	0x5f, 0x43, 0x61, 0x76, 0x61, 0x6c, 0x72, 0x79, 0x10, 0x03, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_slg_proto_rawDescOnce sync.Once
	file_slg_proto_rawDescData = file_slg_proto_rawDesc
)

func file_slg_proto_rawDescGZIP() []byte {
	file_slg_proto_rawDescOnce.Do(func() {
		file_slg_proto_rawDescData = protoimpl.X.CompressGZIP(file_slg_proto_rawDescData)
	})
	return file_slg_proto_rawDescData
}

var file_slg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_slg_proto_goTypes = []interface{}{
	(FarmerType)(0), // 0: pb.FarmerType
}
var file_slg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_slg_proto_init() }
func file_slg_proto_init() {
	if File_slg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_slg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slg_proto_goTypes,
		DependencyIndexes: file_slg_proto_depIdxs,
		EnumInfos:         file_slg_proto_enumTypes,
	}.Build()
	File_slg_proto = out.File
	file_slg_proto_rawDesc = nil
	file_slg_proto_goTypes = nil
	file_slg_proto_depIdxs = nil
}
