// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: tbg.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 副本类型
type CaveType int32

const (
	CaveType_CAT_None CaveType = 0 //普通副本 读chapter的配置
	// 大闹天宫
	CaveType_CAT_DaNaotianGong CaveType = 1 //读大闹天宫的配置  其他的同理
	// 神兽试炼
	CaveType_CAT_ShenShouShiLian CaveType = 2
	// 通天塔
	CaveType_CAT_TongTianTa CaveType = 3
	// 试炼塔
	CaveType_CAT_ShiLianTa CaveType = 4
	// 世界boss
	CaveType_CAT_ShiJieBoss CaveType = 5
	//最强战队
	CaveType_CAT_ZuiQiangZhanDui CaveType = 6
	//   三皇争锋
	CaveType_CAT_SanHuangZhengFeng CaveType = 7
	//  五帝争锋
	CaveType_CAT_WuDiZhengFeng CaveType = 8
)

// Enum value maps for CaveType.
var (
	CaveType_name = map[int32]string{
		0: "CAT_None",
		1: "CAT_DaNaotianGong",
		2: "CAT_ShenShouShiLian",
		3: "CAT_TongTianTa",
		4: "CAT_ShiLianTa",
		5: "CAT_ShiJieBoss",
		6: "CAT_ZuiQiangZhanDui",
		7: "CAT_SanHuangZhengFeng",
		8: "CAT_WuDiZhengFeng",
	}
	CaveType_value = map[string]int32{
		"CAT_None":              0,
		"CAT_DaNaotianGong":     1,
		"CAT_ShenShouShiLian":   2,
		"CAT_TongTianTa":        3,
		"CAT_ShiLianTa":         4,
		"CAT_ShiJieBoss":        5,
		"CAT_ZuiQiangZhanDui":   6,
		"CAT_SanHuangZhengFeng": 7,
		"CAT_WuDiZhengFeng":     8,
	}
)

func (x CaveType) Enum() *CaveType {
	p := new(CaveType)
	*p = x
	return p
}

func (x CaveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaveType) Descriptor() protoreflect.EnumDescriptor {
	return file_tbg_proto_enumTypes[0].Descriptor()
}

func (CaveType) Type() protoreflect.EnumType {
	return &file_tbg_proto_enumTypes[0]
}

func (x CaveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaveType.Descriptor instead.
func (CaveType) EnumDescriptor() ([]byte, []int) {
	return file_tbg_proto_rawDescGZIP(), []int{0}
}

var File_tbg_proto protoreflect.FileDescriptor

var file_tbg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x62, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a,
	0xce, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x41, 0x54, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x41,
	0x54, 0x5f, 0x44, 0x61, 0x4e, 0x61, 0x6f, 0x74, 0x69, 0x61, 0x6e, 0x47, 0x6f, 0x6e, 0x67, 0x10,
	0x01, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x41, 0x54, 0x5f, 0x53, 0x68, 0x65, 0x6e, 0x53, 0x68, 0x6f,
	0x75, 0x53, 0x68, 0x69, 0x4c, 0x69, 0x61, 0x6e, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x41,
	0x54, 0x5f, 0x54, 0x6f, 0x6e, 0x67, 0x54, 0x69, 0x61, 0x6e, 0x54, 0x61, 0x10, 0x03, 0x12, 0x11,
	0x0a, 0x0d, 0x43, 0x41, 0x54, 0x5f, 0x53, 0x68, 0x69, 0x4c, 0x69, 0x61, 0x6e, 0x54, 0x61, 0x10,
	0x04, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x41, 0x54, 0x5f, 0x53, 0x68, 0x69, 0x4a, 0x69, 0x65, 0x42,
	0x6f, 0x73, 0x73, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x41, 0x54, 0x5f, 0x5a, 0x75, 0x69,
	0x51, 0x69, 0x61, 0x6e, 0x67, 0x5a, 0x68, 0x61, 0x6e, 0x44, 0x75, 0x69, 0x10, 0x06, 0x12, 0x19,
	0x0a, 0x15, 0x43, 0x41, 0x54, 0x5f, 0x53, 0x61, 0x6e, 0x48, 0x75, 0x61, 0x6e, 0x67, 0x5a, 0x68,
	0x65, 0x6e, 0x67, 0x46, 0x65, 0x6e, 0x67, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x41, 0x54,
	0x5f, 0x57, 0x75, 0x44, 0x69, 0x5a, 0x68, 0x65, 0x6e, 0x67, 0x46, 0x65, 0x6e, 0x67, 0x10, 0x08,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tbg_proto_rawDescOnce sync.Once
	file_tbg_proto_rawDescData = file_tbg_proto_rawDesc
)

func file_tbg_proto_rawDescGZIP() []byte {
	file_tbg_proto_rawDescOnce.Do(func() {
		file_tbg_proto_rawDescData = protoimpl.X.CompressGZIP(file_tbg_proto_rawDescData)
	})
	return file_tbg_proto_rawDescData
}

var file_tbg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tbg_proto_goTypes = []interface{}{
	(CaveType)(0), // 0: pb.CaveType
}
var file_tbg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tbg_proto_init() }
func file_tbg_proto_init() {
	if File_tbg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tbg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tbg_proto_goTypes,
		DependencyIndexes: file_tbg_proto_depIdxs,
		EnumInfos:         file_tbg_proto_enumTypes,
	}.Build()
	File_tbg_proto = out.File
	file_tbg_proto_rawDesc = nil
	file_tbg_proto_goTypes = nil
	file_tbg_proto_depIdxs = nil
}
