// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: Z0_Common.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RankType int32

const (
	RankType_PlayerRankWeek  RankType = 0 // 玩家周排名
	RankType_PlayerRankMonth RankType = 1 // 玩家月排名
	// 玩家段位排名
	RankType_PlayerRanking RankType = 2
)

// Enum value maps for RankType.
var (
	RankType_name = map[int32]string{
		0: "PlayerRankWeek",
		1: "PlayerRankMonth",
		2: "PlayerRanking",
	}
	RankType_value = map[string]int32{
		"PlayerRankWeek":  0,
		"PlayerRankMonth": 1,
		"PlayerRanking":   2,
	}
)

func (x RankType) Enum() *RankType {
	p := new(RankType)
	*p = x
	return p
}

func (x RankType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankType) Descriptor() protoreflect.EnumDescriptor {
	return file_Z0_Common_proto_enumTypes[0].Descriptor()
}

func (RankType) Type() protoreflect.EnumType {
	return &file_Z0_Common_proto_enumTypes[0]
}

func (x RankType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankType.Descriptor instead.
func (RankType) EnumDescriptor() ([]byte, []int) {
	return file_Z0_Common_proto_rawDescGZIP(), []int{0}
}

type ErrCode int32

const (
	ErrCode_Success ErrCode = 0 //成功
	// 通用请求错误
	ErrCode_CommonFail ErrCode = 1 //失败
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "Success",
		1: "CommonFail",
	}
	ErrCode_value = map[string]int32{
		"Success":    0,
		"CommonFail": 1,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_Z0_Common_proto_enumTypes[1].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_Z0_Common_proto_enumTypes[1]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_Z0_Common_proto_rawDescGZIP(), []int{1}
}

type Common struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Common) Reset() {
	*x = Common{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z0_Common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Common) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Common) ProtoMessage() {}

func (x *Common) ProtoReflect() protoreflect.Message {
	mi := &file_Z0_Common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Common.ProtoReflect.Descriptor instead.
func (*Common) Descriptor() ([]byte, []int) {
	return file_Z0_Common_proto_rawDescGZIP(), []int{0}
}

// 玩家数据
type OpenVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// openId
	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	// 用户头像
	AvatarUrl string `protobuf:"bytes,2,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	// 昵称
	NickName string `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	// 总礼物值
	GiftValue int64 `protobuf:"varint,4,opt,name=giftValue,proto3" json:"giftValue,omitempty"`
	// 这周积分
	Score int64 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	// 当周排名
	Rank int32 `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	// 这胜点
	WinPoint int64 `protobuf:"varint,7,opt,name=winPoint,proto3" json:"winPoint,omitempty"`
	// 这月积分
	MonthScore int64 `protobuf:"varint,8,opt,name=monthScore,proto3" json:"monthScore,omitempty"`
	// 当月排名
	MonthRank int32 `protobuf:"varint,9,opt,name=monthRank,proto3" json:"monthRank,omitempty"`
	// 上次更新时间
	LastUpdateTime int64 `protobuf:"varint,12,opt,name=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"`
}

func (x *OpenVo) Reset() {
	*x = OpenVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z0_Common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenVo) ProtoMessage() {}

func (x *OpenVo) ProtoReflect() protoreflect.Message {
	mi := &file_Z0_Common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenVo.ProtoReflect.Descriptor instead.
func (*OpenVo) Descriptor() ([]byte, []int) {
	return file_Z0_Common_proto_rawDescGZIP(), []int{1}
}

func (x *OpenVo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *OpenVo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *OpenVo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *OpenVo) GetGiftValue() int64 {
	if x != nil {
		return x.GiftValue
	}
	return 0
}

func (x *OpenVo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *OpenVo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *OpenVo) GetWinPoint() int64 {
	if x != nil {
		return x.WinPoint
	}
	return 0
}

func (x *OpenVo) GetMonthScore() int64 {
	if x != nil {
		return x.MonthScore
	}
	return 0
}

func (x *OpenVo) GetMonthRank() int32 {
	if x != nil {
		return x.MonthRank
	}
	return 0
}

func (x *OpenVo) GetLastUpdateTime() int64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

//主播信息存档的
type AnchorDBInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 唯一id
	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// 昵称
	NickName string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	// 头像
	HeadUrl string `protobuf:"bytes,3,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
	// 游戏ID
	GameId int32 `protobuf:"varint,4,opt,name=gameId,proto3" json:"gameId,omitempty"`
	// 平台
	PlatformId int32 `protobuf:"varint,5,opt,name=platformId,proto3" json:"platformId,omitempty"`
	// 游戏模式(官游/野游)
	ModeId int32 `protobuf:"varint,6,opt,name=modeId,proto3" json:"modeId,omitempty"`
	// 总礼物值
	AllGiftValue float64 `protobuf:"fixed64,7,opt,name=allGiftValue,proto3" json:"allGiftValue,omitempty"`
}

func (x *AnchorDBInfo) Reset() {
	*x = AnchorDBInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z0_Common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnchorDBInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorDBInfo) ProtoMessage() {}

func (x *AnchorDBInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Z0_Common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorDBInfo.ProtoReflect.Descriptor instead.
func (*AnchorDBInfo) Descriptor() ([]byte, []int) {
	return file_Z0_Common_proto_rawDescGZIP(), []int{2}
}

func (x *AnchorDBInfo) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AnchorDBInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *AnchorDBInfo) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

func (x *AnchorDBInfo) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *AnchorDBInfo) GetPlatformId() int32 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *AnchorDBInfo) GetModeId() int32 {
	if x != nil {
		return x.ModeId
	}
	return 0
}

func (x *AnchorDBInfo) GetAllGiftValue() float64 {
	if x != nil {
		return x.AllGiftValue
	}
	return 0
}

type OpenBaseVo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// openId
	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	// 用户头像
	AvatarUrl string `protobuf:"bytes,2,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	// 昵称
	NickName string `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	// 评论
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *OpenBaseVo) Reset() {
	*x = OpenBaseVo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z0_Common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenBaseVo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenBaseVo) ProtoMessage() {}

func (x *OpenBaseVo) ProtoReflect() protoreflect.Message {
	mi := &file_Z0_Common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenBaseVo.ProtoReflect.Descriptor instead.
func (*OpenBaseVo) Descriptor() ([]byte, []int) {
	return file_Z0_Common_proto_rawDescGZIP(), []int{3}
}

func (x *OpenBaseVo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *OpenBaseVo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *OpenBaseVo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *OpenBaseVo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 玩家继承的下一场的数据
type PlayerInheritInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 玩家id
	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	// 礼物id
	GiftId string `protobuf:"bytes,2,opt,name=giftId,proto3" json:"giftId,omitempty"`
	// 礼物数量
	GiftNum int32 `protobuf:"varint,3,opt,name=giftNum,proto3" json:"giftNum,omitempty"`
	// 名字
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// 头像
	HeadUrl string `protobuf:"bytes,5,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
}

func (x *PlayerInheritInfo) Reset() {
	*x = PlayerInheritInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z0_Common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInheritInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInheritInfo) ProtoMessage() {}

func (x *PlayerInheritInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Z0_Common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInheritInfo.ProtoReflect.Descriptor instead.
func (*PlayerInheritInfo) Descriptor() ([]byte, []int) {
	return file_Z0_Common_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInheritInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *PlayerInheritInfo) GetGiftId() string {
	if x != nil {
		return x.GiftId
	}
	return ""
}

func (x *PlayerInheritInfo) GetGiftNum() int32 {
	if x != nil {
		return x.GiftNum
	}
	return 0
}

func (x *PlayerInheritInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInheritInfo) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

var File_Z0_Common_proto protoreflect.FileDescriptor

var file_Z0_Common_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x5a, 0x30, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x08, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22,
	0xa4, 0x02, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x56, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70,
	0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x67, 0x69, 0x66, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x67, 0x69, 0x66, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x26,
	0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x0c, 0x41, 0x6e, 0x63, 0x68, 0x6f,
	0x72, 0x44, 0x42, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61,
	0x6c, 0x6c, 0x47, 0x69, 0x66, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x47, 0x69, 0x66, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x78, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x56, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x11, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x68, 0x65, 0x72, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x69, 0x66, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x69, 0x66, 0x74, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x69, 0x66, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x67, 0x69, 0x66, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x2a, 0x46, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x61, 0x6e,
	0x6b, 0x57, 0x65, 0x65, 0x6b, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x61, 0x6e, 0x6b, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x2a,
	0x26, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Z0_Common_proto_rawDescOnce sync.Once
	file_Z0_Common_proto_rawDescData = file_Z0_Common_proto_rawDesc
)

func file_Z0_Common_proto_rawDescGZIP() []byte {
	file_Z0_Common_proto_rawDescOnce.Do(func() {
		file_Z0_Common_proto_rawDescData = protoimpl.X.CompressGZIP(file_Z0_Common_proto_rawDescData)
	})
	return file_Z0_Common_proto_rawDescData
}

var file_Z0_Common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Z0_Common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Z0_Common_proto_goTypes = []interface{}{
	(RankType)(0),             // 0: pb.RankType
	(ErrCode)(0),              // 1: pb.ErrCode
	(*Common)(nil),            // 2: pb.Common
	(*OpenVo)(nil),            // 3: pb.OpenVo
	(*AnchorDBInfo)(nil),      // 4: pb.AnchorDBInfo
	(*OpenBaseVo)(nil),        // 5: pb.OpenBaseVo
	(*PlayerInheritInfo)(nil), // 6: pb.PlayerInheritInfo
}
var file_Z0_Common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Z0_Common_proto_init() }
func file_Z0_Common_proto_init() {
	if File_Z0_Common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Z0_Common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Common); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Z0_Common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Z0_Common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnchorDBInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Z0_Common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenBaseVo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Z0_Common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInheritInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Z0_Common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Z0_Common_proto_goTypes,
		DependencyIndexes: file_Z0_Common_proto_depIdxs,
		EnumInfos:         file_Z0_Common_proto_enumTypes,
		MessageInfos:      file_Z0_Common_proto_msgTypes,
	}.Build()
	File_Z0_Common_proto = out.File
	file_Z0_Common_proto_rawDesc = nil
	file_Z0_Common_proto_goTypes = nil
	file_Z0_Common_proto_depIdxs = nil
}
