// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: Z12_LoginResp.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 客户端登录回复
type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrMsg string `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"` //消息code 0成功 1失败
	// 房间号
	RoomId string `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	// 时间戳(秒)
	ServerTime int32 `protobuf:"varint,3,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	// 主播数据
	AnchorDB *AnchorDBInfo `protobuf:"bytes,4,opt,name=anchorDB,proto3" json:"anchorDB,omitempty"`
	// 战斗是否未结算
	IsBattleUnsettle bool `protobuf:"varint,5,opt,name=isBattleUnsettle,proto3" json:"isBattleUnsettle,omitempty"` // true 是没有结算 false 是已经结算或没有开始
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z12_LoginResp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_Z12_LoginResp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_Z12_LoginResp_proto_rawDescGZIP(), []int{0}
}

func (x *LoginResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *LoginResp) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LoginResp) GetServerTime() int32 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *LoginResp) GetAnchorDB() *AnchorDBInfo {
	if x != nil {
		return x.AnchorDB
	}
	return nil
}

func (x *LoginResp) GetIsBattleUnsettle() bool {
	if x != nil {
		return x.IsBattleUnsettle
	}
	return false
}

var File_Z12_LoginResp_proto protoreflect.FileDescriptor

var file_Z12_LoginResp_proto_rawDesc = []byte{
	0x0a, 0x13, 0x5a, 0x31, 0x32, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x5a, 0x30, 0x5f, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x01, 0x0a, 0x09, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x61, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x44, 0x42, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x44, 0x42, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x61, 0x6e,
	0x63, 0x68, 0x6f, 0x72, 0x44, 0x42, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x73, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x55, 0x6e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x10, 0x69, 0x73, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x55, 0x6e, 0x73, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Z12_LoginResp_proto_rawDescOnce sync.Once
	file_Z12_LoginResp_proto_rawDescData = file_Z12_LoginResp_proto_rawDesc
)

func file_Z12_LoginResp_proto_rawDescGZIP() []byte {
	file_Z12_LoginResp_proto_rawDescOnce.Do(func() {
		file_Z12_LoginResp_proto_rawDescData = protoimpl.X.CompressGZIP(file_Z12_LoginResp_proto_rawDescData)
	})
	return file_Z12_LoginResp_proto_rawDescData
}

var file_Z12_LoginResp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Z12_LoginResp_proto_goTypes = []interface{}{
	(*LoginResp)(nil),    // 0: pb.LoginResp
	(*AnchorDBInfo)(nil), // 1: pb.AnchorDBInfo
}
var file_Z12_LoginResp_proto_depIdxs = []int32{
	1, // 0: pb.LoginResp.anchorDB:type_name -> pb.AnchorDBInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Z12_LoginResp_proto_init() }
func file_Z12_LoginResp_proto_init() {
	if File_Z12_LoginResp_proto != nil {
		return
	}
	file_Z0_Common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Z12_LoginResp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Z12_LoginResp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Z12_LoginResp_proto_goTypes,
		DependencyIndexes: file_Z12_LoginResp_proto_depIdxs,
		MessageInfos:      file_Z12_LoginResp_proto_msgTypes,
	}.Build()
	File_Z12_LoginResp_proto = out.File
	file_Z12_LoginResp_proto_rawDesc = nil
	file_Z12_LoginResp_proto_goTypes = nil
	file_Z12_LoginResp_proto_depIdxs = nil
}
