// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: Z14_PlayerJoinNotify.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 观众加入
type PlayerJoinNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenList []*OpenVo `protobuf:"bytes,1,rep,name=openList,proto3" json:"openList,omitempty"`
}

func (x *PlayerJoinNotify) Reset() {
	*x = PlayerJoinNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z14_PlayerJoinNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerJoinNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinNotify) ProtoMessage() {}

func (x *PlayerJoinNotify) ProtoReflect() protoreflect.Message {
	mi := &file_Z14_PlayerJoinNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinNotify.ProtoReflect.Descriptor instead.
func (*PlayerJoinNotify) Descriptor() ([]byte, []int) {
	return file_Z14_PlayerJoinNotify_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerJoinNotify) GetOpenList() []*OpenVo {
	if x != nil {
		return x.OpenList
	}
	return nil
}

var File_Z14_PlayerJoinNotify_proto protoreflect.FileDescriptor

var file_Z14_PlayerJoinNotify_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x5a, 0x31, 0x34, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0f, 0x5a, 0x30, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3a, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x26, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x56, 0x6f, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Z14_PlayerJoinNotify_proto_rawDescOnce sync.Once
	file_Z14_PlayerJoinNotify_proto_rawDescData = file_Z14_PlayerJoinNotify_proto_rawDesc
)

func file_Z14_PlayerJoinNotify_proto_rawDescGZIP() []byte {
	file_Z14_PlayerJoinNotify_proto_rawDescOnce.Do(func() {
		file_Z14_PlayerJoinNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_Z14_PlayerJoinNotify_proto_rawDescData)
	})
	return file_Z14_PlayerJoinNotify_proto_rawDescData
}

var file_Z14_PlayerJoinNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Z14_PlayerJoinNotify_proto_goTypes = []interface{}{
	(*PlayerJoinNotify)(nil), // 0: pb.PlayerJoinNotify
	(*OpenVo)(nil),           // 1: pb.OpenVo
}
var file_Z14_PlayerJoinNotify_proto_depIdxs = []int32{
	1, // 0: pb.PlayerJoinNotify.openList:type_name -> pb.OpenVo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Z14_PlayerJoinNotify_proto_init() }
func file_Z14_PlayerJoinNotify_proto_init() {
	if File_Z14_PlayerJoinNotify_proto != nil {
		return
	}
	file_Z0_Common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Z14_PlayerJoinNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerJoinNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Z14_PlayerJoinNotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Z14_PlayerJoinNotify_proto_goTypes,
		DependencyIndexes: file_Z14_PlayerJoinNotify_proto_depIdxs,
		MessageInfos:      file_Z14_PlayerJoinNotify_proto_msgTypes,
	}.Build()
	File_Z14_PlayerJoinNotify_proto = out.File
	file_Z14_PlayerJoinNotify_proto_rawDesc = nil
	file_Z14_PlayerJoinNotify_proto_goTypes = nil
	file_Z14_PlayerJoinNotify_proto_depIdxs = nil
}
