// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: Z20_RankResp.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 查看排行榜回复
type RankResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrMsg      string     `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"` //消息code 0成功 1失败
	RankType    RankType   `protobuf:"varint,2,opt,name=RankType,proto3,enum=pb.RankType" json:"RankType,omitempty"`
	RanInfoList []*RanInfo `protobuf:"bytes,3,rep,name=RanInfoList,proto3" json:"RanInfoList,omitempty"`
}

func (x *RankResp) Reset() {
	*x = RankResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z20_RankResp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResp) ProtoMessage() {}

func (x *RankResp) ProtoReflect() protoreflect.Message {
	mi := &file_Z20_RankResp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResp.ProtoReflect.Descriptor instead.
func (*RankResp) Descriptor() ([]byte, []int) {
	return file_Z20_RankResp_proto_rawDescGZIP(), []int{0}
}

func (x *RankResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *RankResp) GetRankType() RankType {
	if x != nil {
		return x.RankType
	}
	return RankType_PlayerRankWeek
}

func (x *RankResp) GetRanInfoList() []*RanInfo {
	if x != nil {
		return x.RanInfoList
	}
	return nil
}

type RanInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 名字
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 头像
	HeadUrl string `protobuf:"bytes,2,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
	// 分
	Score int64 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	// 胜点
	WinPoint int64 `protobuf:"varint,4,opt,name=winPoint,proto3" json:"winPoint,omitempty"`
}

func (x *RanInfo) Reset() {
	*x = RanInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z20_RankResp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RanInfo) ProtoMessage() {}

func (x *RanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Z20_RankResp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RanInfo.ProtoReflect.Descriptor instead.
func (*RanInfo) Descriptor() ([]byte, []int) {
	return file_Z20_RankResp_proto_rawDescGZIP(), []int{1}
}

func (x *RanInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RanInfo) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

func (x *RanInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RanInfo) GetWinPoint() int64 {
	if x != nil {
		return x.WinPoint
	}
	return 0
}

var File_Z20_RankResp_proto protoreflect.FileDescriptor

var file_Z20_RankResp_proto_rawDesc = []byte{
	0x0a, 0x12, 0x5a, 0x32, 0x30, 0x5f, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x5a, 0x30, 0x5f, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x08, 0x52, 0x61, 0x6e,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a,
	0x08, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x52,
	0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x52, 0x61, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x69, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x69, 0x6e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_Z20_RankResp_proto_rawDescOnce sync.Once
	file_Z20_RankResp_proto_rawDescData = file_Z20_RankResp_proto_rawDesc
)

func file_Z20_RankResp_proto_rawDescGZIP() []byte {
	file_Z20_RankResp_proto_rawDescOnce.Do(func() {
		file_Z20_RankResp_proto_rawDescData = protoimpl.X.CompressGZIP(file_Z20_RankResp_proto_rawDescData)
	})
	return file_Z20_RankResp_proto_rawDescData
}

var file_Z20_RankResp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Z20_RankResp_proto_goTypes = []interface{}{
	(*RankResp)(nil), // 0: pb.RankResp
	(*RanInfo)(nil),  // 1: pb.RanInfo
	(RankType)(0),    // 2: pb.RankType
}
var file_Z20_RankResp_proto_depIdxs = []int32{
	2, // 0: pb.RankResp.RankType:type_name -> pb.RankType
	1, // 1: pb.RankResp.RanInfoList:type_name -> pb.RanInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Z20_RankResp_proto_init() }
func file_Z20_RankResp_proto_init() {
	if File_Z20_RankResp_proto != nil {
		return
	}
	file_Z0_Common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Z20_RankResp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Z20_RankResp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RanInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Z20_RankResp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Z20_RankResp_proto_goTypes,
		DependencyIndexes: file_Z20_RankResp_proto_depIdxs,
		MessageInfos:      file_Z20_RankResp_proto_msgTypes,
	}.Build()
	File_Z20_RankResp_proto = out.File
	file_Z20_RankResp_proto_rawDesc = nil
	file_Z20_RankResp_proto_goTypes = nil
	file_Z20_RankResp_proto_depIdxs = nil
}
