// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: Z6_PongResp.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 心跳
type PongResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrMsg string `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"` //消息code 0成功 1失败
	// 服务端当前时间
	ServerTime int64 `protobuf:"varint,2,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
}

func (x *PongResp) Reset() {
	*x = PongResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Z6_PongResp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResp) ProtoMessage() {}

func (x *PongResp) ProtoReflect() protoreflect.Message {
	mi := &file_Z6_PongResp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResp.ProtoReflect.Descriptor instead.
func (*PongResp) Descriptor() ([]byte, []int) {
	return file_Z6_PongResp_proto_rawDescGZIP(), []int{0}
}

func (x *PongResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *PongResp) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_Z6_PongResp_proto protoreflect.FileDescriptor

var file_Z6_PongResp_proto_rawDesc = []byte{
	0x0a, 0x11, 0x5a, 0x36, 0x5f, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x42, 0x0a, 0x08, 0x50, 0x6f, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Z6_PongResp_proto_rawDescOnce sync.Once
	file_Z6_PongResp_proto_rawDescData = file_Z6_PongResp_proto_rawDesc
)

func file_Z6_PongResp_proto_rawDescGZIP() []byte {
	file_Z6_PongResp_proto_rawDescOnce.Do(func() {
		file_Z6_PongResp_proto_rawDescData = protoimpl.X.CompressGZIP(file_Z6_PongResp_proto_rawDescData)
	})
	return file_Z6_PongResp_proto_rawDescData
}

var file_Z6_PongResp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Z6_PongResp_proto_goTypes = []interface{}{
	(*PongResp)(nil), // 0: pb.PongResp
}
var file_Z6_PongResp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Z6_PongResp_proto_init() }
func file_Z6_PongResp_proto_init() {
	if File_Z6_PongResp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Z6_PongResp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Z6_PongResp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Z6_PongResp_proto_goTypes,
		DependencyIndexes: file_Z6_PongResp_proto_depIdxs,
		MessageInfos:      file_Z6_PongResp_proto_msgTypes,
	}.Build()
	File_Z6_PongResp_proto = out.File
	file_Z6_PongResp_proto_rawDesc = nil
	file_Z6_PongResp_proto_goTypes = nil
	file_Z6_PongResp_proto_depIdxs = nil
}
